### ISSUE TITLE
Missing instructions for migrating from le_node?

### ISSUE THREAD

**Issue by bradvogel** [rapid7/r7insight_node#33]
I tried using this as a drop-in replacement for le_node using the following code:

Original code using `le_node`:
```js
const Logger = require('le_node');
const logger = new Logger({ token: '<token>' });
logger.warning('test message');
```

Same code using `r7insight_node`:
```js
// Does not work
const Logger = require('r7insight_node');
const logger = new Logger({ token: '<token>' , region: 'us'});
logger.warning('test message');
```

However, in digging in, I realized I need to pass the `host`:
```js
// Works
const Logger = require('r7insight_node');
const logger = new Logger({ token: '<token>' , host: 'data.logentries.com' });
logger.warning('test message');
```

Should this be documented somewhere in the readme?

**Comment by sbialkowski-r7** [comment]
Hey @bradvogel, in your second code snippet could you try changing the region to `eu`?

Logentries used to be EU-only, and specifying the host as you did and setting the region to `eu` should have the same functionality.

Let me know if this works and i'll update any READMEs, just curious, did you use this migration guide?
https://github.com/rapid7/r7insight_node/wiki/2.0-Migration-Guide

**Comment by bradvogel** [comment]
I see now. I didn't realize the region should have been 'eu'. The following works:

```
// Works
const Logger = require('r7insight_node');
const logger = new Logger({ token: '<token>' , region: 'eu'});
logger.warning('test message');
```

I saw the migration guide, though it makes no mention of what the region should be for users migrating from `le_node`.
